import org.gradle.api.tasks.Exec

val npmInstall = tasks.register<Exec>("npmInstall") {
    group = "build"
    description = "Installs npm dependencies using 'npm ci'."
    workingDir = projectDir
    commandLine("npm", "ci", "--prefer-offline")
    inputs.file("package.json")
    inputs.file("package-lock.json")
    // node_modules is generated by npm ci; use outputs to track freshness
    outputs.dir("node_modules")
}

val npmBuild = tasks.register<Exec>("npmBuild") {
    group = "build"
    description = "Builds the frontend project using 'npm run build'."
    dependsOn(npmInstall)
    workingDir = projectDir
    commandLine("npm", "run", "build")
    inputs.dir("src")
    inputs.file("index.html")
    inputs.file("vite.config.ts")
    inputs.file("tsconfig.json")
    outputs.dir("dist")
}

tasks.register("build") {
    group = "build"
    description = "Assembles the frontend project."
    dependsOn(npmBuild)
}
