[versions]
ktorVersion = "3.4.2"
kotlinVersion = "2.3.20"
logbackVersion = "1.5.32"
logstashVersion = "9.0"
kotlinLoggingVersion = "8.0.01"
koinVersion = "4.2.0"
mongoVersion = "5.6.4"
julToSlfjVersion = "2.0.17"
jsonKotlinSchemaVersion = "0.57"
mockkVersion = "1.14.9"
kotestVersion = "5.9.0"
kotlinxCoroutinesTestVersion = "1.10.1"
junitVersion = "5.10.0"
sonarqubeVersion = "7.2.3.7755"
ktlintPluginVersion = "14.2.0"
testcontainersVersion = "1.21.4"
kotestExtensionsVersion = "2.0.2"
openTelemetryVersion = "1.47.0"
openTelemetryInstrumentationVersion = "2.13.0-alpha"
openTelemetryInstrumentationAnnotationsVersion = "2.13.0"
kotlinxSerializationVersion = "1.8.0"

# Documentation site
nodeGradleVersion = "7.1.0"
nodeVersion = "22.12.0"

[libraries]
# KTOR
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktorVersion" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktorVersion" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktorVersion" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktorVersion" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktorVersion" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers-jvm", version.ref = "ktorVersion" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktorVersion" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktorVersion" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation-jvm", version.ref = "ktorVersion" }

# Logging
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashVersion" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLoggingVersion" }

# Serialization:
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationVersion" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktorVersion" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktorVersion" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktorVersion" }

# Koin:
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koinVersion" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koinVersion" }

# Mongo DB
mongodb-driver-kotlin-sync = { module = "org.mongodb:mongodb-driver-kotlin-sync", version.ref = "mongoVersion" }
mongodb-driver-kotlin-coroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongoVersion" }
mongodb-bson = { module = "org.mongodb:bson", version.ref = "mongoVersion" }
mongodb-bson-kotlinx = { module = "org.mongodb:bson-kotlinx", version.ref = "mongoVersion" }

# Bridge from java jul logging to slf (logback) logging:
jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "julToSlfjVersion" }

# Json schema validation:
json-kotlin-schema = { module = "net.pwall.json:json-kotlin-schema", version.ref = "jsonKotlinSchemaVersion" }

# Http client
ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktorVersion" }
ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktorVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging-jvm", version.ref = "ktorVersion" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktorVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorVersion" }

# Unit Testing & Mocking
testcontainers-mongodb = { module = "org.testcontainers:mongodb", version.ref = "testcontainersVersion" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainersVersion" }
kotest-extensions-testcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version.ref = "kotestExtensionsVersion" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitVersion" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotestVersion" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotestVersion" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotestVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTestVersion" }
# Koin tests:
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinVersion" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koinVersion" }
# Mock for client requests
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktorVersion" }

# Tracing
opentelemetry-bom = { module = "io.opentelemetry:opentelemetry-bom", version.ref = "openTelemetryVersion" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api" }
opentelemetry-sdk = { module = "io.opentelemetry:opentelemetry-sdk" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
opentelemetry-instrumentation-mongo = { module = "io.opentelemetry.instrumentation:opentelemetry-mongo-3.1", version.ref = "openTelemetryInstrumentationVersion" }
opentelemetry-extension-kotlin = { module = "io.opentelemetry:opentelemetry-extension-kotlin" }
opentelemetry-instrumentation-logback = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0", version.ref = "openTelemetryInstrumentationVersion" }
opentelemetry-instrumentation-annotations = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations", version.ref = "openTelemetryInstrumentationAnnotationsVersion" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
ktor = { id = "io.ktor.plugin", version.ref = "ktorVersion" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPluginVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqubeVersion" }
node-gradle = { id = "com.github.node-gradle.node", version.ref = "nodeGradleVersion" }
